### ISSUE TITLE
Incorrect result of \Composer\Semver\Constraint\ConstraintInterface::matches()

### ISSUE THREAD

**Issue by viktym** [composer/semver#126] opened 2021-05-17 21:51 UTC
\Composer\Semver\Constraint\ConstraintInterface::matches returns false-positive result if '||' is used in constraint.

**Code:**
```
 $versionParser = new \Composer\Semver\VersionParser();
 $constraint1 = $versionParser->parseConstraints('>=2.3.1 <2.3.4');
 $constraint2 = $versionParser->parseConstraints('2.3.0 || >=2.3.4 <2.4.2');
 var_dump($constraint1->matches($constraint2));
```
**Expected result** (version 1.7.2):
false

**Actual result** (version 3.2.4):
true

**UPD**
Looks like it's some edge case. If we use '10.0.0 || >=2.3.4 <2.4.2' in example above then the result is correct. 
But in case of '1.0.0 || >=2.3.4 <2.4.2' the result is wrong. If the value < 2.3.1 then we have an issue.

**Comment by naderman** [comment] 2021-05-21 16:23
The problem is actually more fundamental. Currently `[>1 && <2]->matches([<1 || >2])` returns true as well, the problem is with calling matches on a conjunctive multi constraint with a disjunctive multiconstraint as input.

**Comment by Seldaek** [comment] 2021-05-24 10:41
Fixed by https://github.com/composer/semver/pull/127

**Closed by Seldaek** 2021-05-24 10:41 UTC
Labels: bug
