### ISSUE TITLE
MultiConstraint bounds return partly wrong versions

### ISSUE THREAD

**Issue by simonberger** [composer/semver#105] opened 2020-08-24 01:11 UTC
I just tried to use the `getLowerBound` and `getUpperBound` methods of the Constraint classes I received from `MultiConstraint::getConstraints` and got some unexpected results when testing the following version string `^1.5|^2.0`.
It has two constraints reporting bounds from 1.5 to infinity and 0.0 to 3.0.
I understand why this is happening there and guess it is already known. If this can't be fixed easily it would from my point of view be better to throw an exception than to return wrong version informations.

**Comment by Seldaek** [comment] 2020-08-24 09:08
If you look at the individual constraints forming the multi-constraint, you'll get that. This is not a bug IMO.

If you get the lower and upper bounds of the multiconstraint (which is a conjunction of those two sub-constraints `1.5 to +inf` AND `0 to <3`), you should get 1.5 and 3.0, which is correct.

**Comment by GrahamCampbell** [comment] 2020-08-24 09:47
Yeh, I agree this is not a bug.

**Comment by simonberger** [comment] 2020-08-24 09:56
Yeah I saw the underlying structure of those constraints. It might be "by design" but I can't agree that this is no bug. From a consumer point of view I want to get the boundaries of every step and those version information I receive are wrong.

Using the boundaries of the multi constraint gives me other data which lack gaps between the intervals (this example surely had no gaps).

**Comment by simonberger** [comment] 2020-08-24 10:10
I understand where you are pointing to. The two constraints itself >= 1.5 and < 3.0 are viewed in isolation already wrong but they can be seen as a whole and interpreted accordingly. That does not work for the bounds though.

For me this is no terrible issue I just wanted to report it and already guessed that this will be closed unchanged. It is no big problem for me if I can't change your mind. ;)

**Comment by Seldaek** [comment] 2020-08-24 10:55
The bounds are really just bounds and are somewhat simplistic. If you want
full interval coverage with gaps look at the Intervals class it should help.

**Comment by Seldaek** [comment] 2020-08-25 05:45
I meant https://github.com/composer/semver/blob/master/src/Intervals.php#L262-L281 specifically - anyway closing here.

**Closed by Seldaek** 2020-08-25 05:45 UTC
