### ISSUE TITLE
VersionParser throws UnexpectedValueException on 20150920.0.0

### ISSUE THREAD

**Issue by emaijala** [composer/semver#32] opened 2015-12-19 18:34 UTC
Composer unable to install google-closure-compiler package with the composer-asset-plugin due to a version number parsing issue. I'm trying to install the npm packages of Angular2, but it seems that the VersionParser class thinks the version number of the package (20150920.0.0) is invalid. Looks to me the check is too strict in that it only allows the major version to be up to five digits, but just changing the check makes a date-based version string fail a phpunit test, so I wasn't quite sure how this should be handled.

Here's a minimal compos er.json to reproduce the problem:

```
{
    "require": {
        "npm-asset/google-closure-compiler": "20150920.0.0"
    }
}
```

composer -vvv update output:

```
composer -vvv update
Reading ./composer.json
Loading config file /Users/ere/.composer/config.json
Loading config file /Users/ere/.composer/auth.json
Loading config file ./composer.json
Executing command (/Users/ere/src/composertest): git describe --exact-match --tags
Executing command (/Users/ere/src/composertest): git branch --no-color --no-abbrev -v
Executing command (/Users/ere/src/composertest): hg branch
Executing command (/Users/ere/src/composertest): svn info --xml
Reading ./composer.json
Loading config file /Users/ere/.composer/config.json
Loading config file /Users/ere/.composer/auth.json
Loading config file ./composer.json
Executing command (/Users/ere/src/composertest): git describe --exact-match --tags
Executing command (/Users/ere/src/composertest): git branch --no-color --no-abbrev -v
Executing command (/Users/ere/src/composertest): hg branch
Executing command (/Users/ere/src/composertest): svn info --xml



  [UnexpectedValueException]
  Could not parse version constraint 20150920.0.0: Invalid version string "20150920.0.0"



Exception trace:
 () at phar:///usr/local/bin/composer/vendor/composer/semver/src/VersionParser.php:467
 Composer\Semver\VersionParser->parseConstraint() at phar:///usr/local/bin/composer/vendor/composer/semver/src/VersionParser.php:248
 Composer\Semver\VersionParser->parseConstraints() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:234
 Composer\Package\Loader\ArrayLoader->parseLinks() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:124
 Composer\Package\Loader\ArrayLoader->load() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:86
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/local/bin/composer/src/Composer/Factory.php:284
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer/src/Composer/Factory.php:504
 Composer\Factory::create() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/Command.php:53
 Composer\Command\Command->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:88
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...
```

**Comment by alcohol** [comment] 2015-12-21 07:35
We can't support every single version format that creative people come up with. The version you are trying to use tries to both conform to a datetime based version and a semantic versioning format. What are we supposed to do here? :-\

**Comment by emaijala** [comment] 2015-12-21 15:20
Well, support the format maybe? It may look like a date, but you could argue that it's just a large number, no? At least at semver.org I couldn't find anything that says version number can't exceed five digits. If there's such definition, I stand corrected, but otherwise this limit seems quite arbitrary.

**Comment by alcohol** [comment] 2015-12-21 16:41
The problem is that it makes it hard for us to differentiate between date(time) formats and semver when people start using date(time) inside semver.

**Comment by emaijala** [comment] 2015-12-21 17:47
I understand, but I'm quite sure Google won't change their scheme now. Would it be possible to differentiate between the formats based on the fact that while there are periods in the string, not all the "date" parts have delimiters?

**Comment by Seldaek** [comment] 2016-11-11 12:15
Closing as per https://github.com/composer/semver/pull/48#issuecomment-259945450

**Closed by Seldaek** 2016-11-11 12:15 UTC
